class Solution {
public:
    string rearrangeString(string s, char x, char y) {
        string ans;
        for(char c: s){
            if(c==y) ans.push_back(c);
        }

        for(char c: s){
            if(c!=x && c!=y ){
                ans.push_back(c);
            } 
        }

        for(char c: s){
            if(c==x){
                ans.push_back(c);
            }
        }
        return ans;


// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 

// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 
// yashika i loveeeeeeeeeee youuuuuuuuuuuu 






    }
};